messager/chat/urls.py
from django.urls import path
from . import views

app_name="chat"
urlpatterns=[
    path('home/',views.chat_homepage,name='homepage'),
    path('delete/',views.chat_deletemessage,name='delete'),
    path('update/',views.chat_updatemessage,name='update')
]

messager/client/urls.py
from django.urls import path
from . import views

app_name="client"
urlpatterns = [
     path('',views.client_login,name='login'),
     path('logout/',views.client_logout,name="logout"),
     path('signup/',views.client_signup,name="signup"),
]

messager/messager/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
     path('admin/', admin.site.urls),
     path('',include('client.urls')),
     path('chat/',include('chat.urls')),
]

messager/chat/models.py
from django.db import models
from client.models import Account,Detail
# Create your models here.

class Message(Detail):
     send_to = models.ForeignKey(Account,on_delete=models.CASCADE ,related_name="resiver")
     send_from = models.ForeignKey(Account,on_delete=models.CASCADE,related_name='sender')
     detail  = models.TextField(blank=True)
     class Meta:
         ordering = ["send_to","send_from","detail","pub_date"]

     def is_self(self):
         if self.send_to == self.send_from:
             return True
         else:
             return False

messager/client/models.py
from django.db import models

# Create your models here.

CITY =[  
         ("aa", "Addis Ababa"),
         ("naz","Nazrēt"),
         ("god", "Gonder"),
         ("mek","Mekele"),
         ("aws","Āwasa"),
         ("dd","Dire Dawa"),
         ("bah","Bahir Dar"),
         ("har", "Harar"),
         ("jig", "Jijiga"),
         ("aso", "Āsosa"),
         ("gam", "Gambēla"),
         ("sem", "Semera")
      ]

GENDER = [
     ('m',"Male"),
     ('f',"Female")
]

class Detail(models.Model):
     pub_date = models.DateTimeField(auto_now_add=True ,null=True)
     class Meta:
         abstract = True

class Myclient(Detail):
     first_name = models.CharField(max_length=50)
     middle_name = models.CharField(max_length=50)
     last_name = models.CharField(max_length=50)
     email     = models.EmailField(unique=True)
     gender    = models.CharField(max_length=3,choices=GENDER,default='m')
     phone     = models.CharField(max_length=12, blank=True,null=True)
     phoneb    = models.CharField(max_length=12, blank=True,null=True)
     coutry    = models.CharField(choices=CITY, max_length=3)
     class Meta:
          ordering = ["first_name","middle_name" ,"last_name",'gender', "email", "coutry","pub_date"]

class Account(Detail):
     user = models.ForeignKey(Myclient,on_delete=models.CASCADE,unique=True)
     password  = models.CharField(max_length=150)
     class Meta:
          ordering = ["user","password","pub_date"]

messager/chat/views.py
from django.shortcuts import render
from . import hadler
from django.http import JsonResponse
from script.decorator import is_loged_out
# Create your views here.

""" chat home page for user"""
@is_loged_out
def chat_homepage(request):
    hadle = hadler.ChatHandler()
    context = {}
    if request.method == "POST":
        hadle.setmessage = False
        if request.POST['action']=="sendmessage":
            #hadle.setmessage = True
            request,client = hadle.send_message(request)
            data = {'firstName':client.send_from.user.first_name, 
                    'lastName':client.send_from.user.last_name,
                    'pubDate':client.pub_date,
                    'detail':client.detail,
                    'iD':f"{client.id}"}
            return JsonResponse(data)

        message,resiver,request =hadle.get_sent_Message(request)
        if message:
            context.update(
                {"messagefound":True}
            )
            context.update({"message_all":message,"resiver":resiver})
    else:
        account = hadle.getAccounts()
        context = {'list_val':account}
    return render(request,'chat/chat_homepage.html',context)

"""client delete message"""
def chat_deletemessage(request):
    hadle = hadler.ChatHandler()
    if request.method == "POST":
        hadle.setmessage = False
        request, success = hadle.delete_message(request)
        data = {'success': success}
        return JsonResponse(data)

"""update delete message"""
def chat_updatemessage(request):
    hadle = hadler.ChatHandler()
    if request.method == "POST":
        request, success = hadle.edit_message(request)
        data = {'success': success}
        return JsonResponse(data)

messager/client/views.py
from django.shortcuts import render,redirect
from .handler import ClientHandler
from script.client_session import SharedHadler
from script.decorator import is_loged_in

# Create your views here.

""" Client Logout """

def client_logout(request):
    shared = SharedHadler()
    request = shared.log_out(request)
    return redirect('client:login')

""" Client login  """
@is_loged_in
def client_login(request):
    hadler = ClientHandler()
    if request.method == "POST":
        hadler.setmessage = True
        request, success = hadler.account_login(request)
        if success: return redirect('chat:homepage')
    return render(request,'client/client_login.html',{})

""" Client Signup"""
@is_loged_in
def client_signup(request):
    hadler = ClientHandler()
    success = False
    if request.method == "POST":
        if request.POST['registor'] == "detail":
            user ,request = hadler.get_client(request)
            if not user:
                success = True
        else:
             hadler.setmessage = True
             request,err = hadler.account_create(request)
             if not err:
                 return redirect('client:login')
    return render(request,'client/client_signup.html',{'city':hadler.get_country(),'gender':hadler.get_gender(),'success':success})

messager/chat/templates/chat/chat_homepage.html
{%extends 'main_index.html'%}
{%load static%}
{%block index%}
{% include 'includes/main_slick.html'%}
<title>Message Home</title>
<style>
  .display_card{
      margin: 10px 10px 0px 10px;
  }
  .btn_message_edit{
    margin: 0px 7px 7px 0px;
  }
</style>
</head>
<body>
{% include 'navbar/home_navbar.html'%}
{% include 'container/top_container.html'%}
<div class="container">
 <div class="row">
<div class="col"></div>
<div class="col-md-5 bg ">
    <div class="col">
      {%if list_val%} 
        <div class="your-class">
              {%for val in list_val%}
                  <div class="container-fluid"> 
                    <div class="row">
                      <div class="col-sm-1">
                          <img src="{%static 'img/user.png'%}" width="50px" height="50px" alt="" srcset="">
                      </div>
                      <div class="col">
                                <form action="" method="post" onclick="this.submit();">{%csrf_token%}
                                  <input type="hidden" name="sendto" value="{{val.id}}">
                                  <input type="hidden" name="action" value="listmessage">
                                  <div class="" style="width: 18rem;">
                                    <div class="card-body">
                                      {%if val.user.email == request.session.account_email%}
                                      <h5 class="card-title">You</h5>
                                      {%else%}
                                      <h5 class="card-title">{{val.user.first_name}} {{val.user.middle_name}} {{val.user.last_name}}</h5>
                                      {%endif%}
                                      
                                      <div style="height: 40px; overflow: hidden;">
                                        <p class="card-text"><small class="text-body-secondary">Last active 3 mins ago</small></p>
                                      </div>
                                    </div>
                                  </div>
                               </form>
                      </div>
                      <div class="col">
    
                      </div>
                    </div>
                  </div>
              {%endfor%}
        </div>
      {%else%}  
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <small> 
            <img src="{%static 'img/user.png'%}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top ">  {{resiver.user.first_name}}
          </small>
          
          <a class="navbar-brand text-body-dark" href="{%url 'chat:homepage'%}">
            <img src="{%static 'img/backspace.png'%}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top "> 
          </a>
        </div>
      </nav>
        {%if messagefound%}

          <div class="your-class">
              {%for val in message_all%}
                <div class="container" id="container{{val.id}}" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample{{val.id}}" aria-expanded="false" aria-controls="collapseExample">
                  <div class="row">
                      <div class="col">
                        <div class="card display_card" style="width: 18rem;" >
                          <nav class="navbar bg-body-tertiary card-header ">
                            <div class="container-fluid">
                              {%if val.send_from.user.email == request.session.account_email%}
                              <small class="text-body-secondary text-start">From:YOU</small> 
                              {%else%}
                              <small class="text-body-secondary text-start">From: {{val.send_from.user.first_name}} {{val.send_from.user.middle_name}} </small> 
                              {%endif%}
                              <div class="d-flex" role="search">
                                <img src="{%static 'img/messeger.png'%}" width="20px" height="20px" alt="" srcset="">
                              </div>
                            </div>
                          </nav>
                          <div class="card-body">
                            <p class="card-text" id="detail{{val.id}}"> {{ val.detail}}</p>
                            <p class="card-text text-end"><small class="text-body-secondary">{{ val.pub_date}}</small></p>
                            
                          </div>
                          </div>
                        </div>
                        {%if val.send_from.user.email == request.session.account_email%}
                        <div class="col bg-light card display_card collapse"  id="collapseExample{{val.id}}">
                          <div class="row">
                            <p class="card-text text-start"><small class="text-body-secondary"> message</small></p>
                          </div>
                          <div class="row">
                            <button class="btn btn-sm btn-secondary btn_message_edit" id="editbtn{{val.id}}" data-bs-toggle="collapse" data-bs-target="#editPost{{val.id}}" aria-expanded="false" aria-controls="collapseExample" aria-expanded="false" aria-controls="collapseExample">Edit</button>
                          </div>
                          <div class="row">
                            <button class="btn btn-sm btn-secondary btn_message_edit" id="{{val.id}}" >Delete</button>
                          </div>
                        </div>
                        <div class="row display_card collapse" id="editPost{{val.id}}">
                          <div class="col " style="width: 18rem;">
                            <form action="" method="post" id="editform{{val.id}}" class="editpostform"> {%csrf_token%}
                                <input type="hidden" name="action" id="action{{val.id}}" value="updatemessage">
                                <input type="hidden" name="editid" id="editid{{val.id}}" value="{{val.id}}">
                                <div class="container-fluid">
                                <div class="row">
                                <div class="col">
                                   <textarea name="detail"  class="form-control"  cols="30" rows="3"  placeholder="new message" required></textarea>
                                </div>      
                                <div class="col-md-2">
                                  <input type="submit" class="btn btn-secondary btn-sm" value="Finish" >  
                                </div> 
                                </div>
                                </div>
                            </form>
                          </div>
    
                        </div>
                        {%endif%}
                    </div>
                    


                </div>
              {%endfor%}
          </div>
        {%else%}
             {% include 'chat/chat_nomessage.html'%}
        {%endif%}
             <nav class="navbar">
              <form action="" method="post"> {%csrf_token%}
                    <input type="hidden" name="action" id="action" value="sendmessage">
                    <input type="hidden" name="sendto" id="sendto" value="{{request.POST.sendto}}">
                    <div class="container-fluid">
                    <div class="row">
                      <div class="col">
                        <textarea name="detail" id='detail' class="form-control"  cols="30" rows="3" placeholder="new message"  required></textarea>
                      </div>      
                      <div class="col-md-2">
                        <input type="submit" class="btn btn-secondary btn-md" value="Send" id="sendbtn">  
                      </div>            
                    </div>
                    </div>
              </form>
             </nav>
      {%endif%}
    </div> 
</div>
<div class="col"> </div>
</div>
</div>
{% include 'container/floor_container.html'%}
<script type="text/javascript">
  $(function()
  {
      const $slider= $('.your-class')
      $slider.on('init', () => {mouseWheel($slider)}).slick({
                                                              infinite: false,
                                                              slidesToShow: 4,
                                                              slidesToScroll: 3,
                                                              vertical:true,
                                                              initialSlide:0,
                                                            })

    function mouseWheel($slider) {
	        $(window).on('wheel', { $slider: $slider }, mouseWheelHandler)
        }

    function mouseWheelHandler(event) {
	    event.preventDefault()
	    const $slider = event.data.$slider
	    const delta = event.originalEvent.deltaY
	    if(delta > 0) {
		    $slider.slick('slickPrev')
	    }
	    else {
		    $slider.slick('slickNext')
	    }
      }

    function getCookie(name) {
    let cookie = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
    return cookie ? cookie[2] : null;
}

    $("button").click(function(e) {
      e.preventDefault()
      const data = new FormData()
      data.append('deleteid', this.id)
      fetch('http://localhost:7000/chat/delete/',{
      method:'post',
      headers: {"X-CSRFToken": getCookie("csrftoken"), },
      body:data}).then((res)=>{
                  return res.json()
                  }).then(data=>{
                      $(`#container${this.id}`).hide()
                  }).catch(err=>{
                      alert(`Error: ${err}`, 'message send error')
                  });
});

    $("#sendbtn").click(function(e){
    e.preventDefault()
    const detail = $('#detail').val()
    const sender = "{{request.session.account_email}}"
    const resiver = $('#sendto').val()
    const data = new FormData();
    data.append('detail', detail);
    data.append('sender', sender);
    data.append('sendto', resiver);
    data.append('action', "sendmessage");

    fetch('.', {
        method: 'post',
        headers: {
            "X-CSRFToken": getCookie("csrftoken"),
        },
        body: data
        }).then((res) => {return res.json()}).then(json => {
                  const detail = json.detail
                  const firstName = json.firstName
                  const lastName = json.lastName
                  const pubDate = json.pubDate
                  const iD = json.iD
                  $slider.slick('slickAdd',
                  `<div class="container" id="container${iD}" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample${iD}" aria-expanded="false" aria-controls="collapseExample">
                  <div class="row">
                      <div class="col">
                        <div class="card display_card" style="width: 18rem;" >
                          <nav class="navbar bg-body-tertiary card-header ">
                            <div class="container-fluid">
                              <small class="text-body-secondary text-start">From: ${firstName} ${lastName}  </small> 
                              <div class="d-flex" role="search">
                                <img src="{%static 'img/messeger.png'%}" width="20px" height="20px" alt="" srcset="">
                              </div>
                            </div>
                          </nav>
                          <div class="card-body">
                            <p class="card-text"> ${detail}</p>
                            <p class="card-text text-end"><small class="text-body-secondary">${pubDate}</small></p>
                            
                          </div>
                          </div>
                        </div>
                        <div class="col bg-light card display_card collapse"  id="collapseExample${iD}">
                          <div class="row">
                            <p class="card-text text-start"><small class="text-body-secondary"> message</small></p>
                          </div>
                          <div class="row">
                            <button class="btn btn-sm btn-secondary btn_message_edit">Edit</button>
                          </div>
                          <div class="row">
                            <button class="btn btn-sm btn-secondary btn_message_edit" id="${iD}"  >Delete</button>
                          </div>
                        </div>
                    </div> </div> `
                  );
                  window.location.reload(true);

        }).catch(err => {
             alert(`Error: ${err}`, 'danger')
        });
      });
  
    $(".editpostform").on('submit',function(e){
      e.preventDefault() 
        // Get all the forms elements and their values in one step
        inputs={};
        input_serialized =  $(this).serializeArray();
        input_serialized.forEach(field => {
        inputs[field.name] = field.value;
        })
      //  alert(inputs.detail)
      const data = new FormData()
      data.append('action', inputs.action)
      data.append('editid', inputs.postid)
      data.append('detail', inputs.detail)
      fetch('http://localhost:7000/chat/update/',{
      method:'post',
      headers: {"X-CSRFToken": getCookie("csrftoken"), },
      body:data}).then((res)=>{
                     return res.json()
                  }).then(data=>{
                       $(`#detail${inputs.editid}`).html(inputs.detail)     
                  }).catch(err=>{
                       alert(`Error: ${err}`, 'message send error')
                  });  
    })
  });
</script>
{%endblock%}

messager/chat/templates/chat/chat_nomessage.html
<div class="">
    <div class="card-body">
       No message Found
    </div>
  </div>

messager/client/templates/client/client_login.html
{%extends 'main_index.html'%}
{%load static%}
{%block index%}
<title>User Login</title>
<style>
    #loginform{
        padding-top: 250px;
    }
</style>
</head>
<body>
{% include 'navbar/main_navbar.html'%}
{% include 'container/top_container.html'%}
<div class="col ">
    <div id="loginform">
        <center class="">
            <form action="" method="post"> {%csrf_token%}
                <div class="" style="width: 40rem;">
                <div class="row mb-3">
                    <label for="email" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-7">
                    <input type="email" class="form-control" id="email" name="email" value="{{request.POST.email}}" required>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="middle_name" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-7">
                    <input type="password" class="form-control" id="middle_name" name="password" required>
                    </div>
                </div>
                <div class="">
                    {% include 'button/main_btn_center.html'%} 
                </div>
            </form>
        </div>
        </center>
        <a class="icon-link icon-link-hover" style="--bs-icon-link-transform: translate3d(0, -.125rem, 0);" href="{% url 'client:signup'%}">
            Sign up
          </a>
    </div>
 
</div>
{% include 'container/floor_container.html'%}
{%endblock%}

messager/client/templates/client/client_signup.html
{%extends 'main_index.html'%}
{%load static%}
{%block index%}
{% include 'includes/main_slick.html'%}
<title>Registor User</title>
<style>
  label{
    font-family: 'Courier New', Courier, monospace;
  }
</style>
</head>
<body>
{% include 'navbar/main_navbar.html'%}
{% include 'container/top_container.html'%}
<div class="col">
    <nav class="navbar navbar-expand-lg bg-body-tertiary ">
        <div class="container-md">
          <label for="" class="navbar-brand " id="title_detail" > Registor User</label>
        </div>
    </nav><br>
    {% include 'container/top_container.html'%}
    <div class="col">
        <form action="" method="post" >{%csrf_token%}
          <div>
              {%include 'collapse/top_collapse.html'%}           
                    <div class="row mb-3">
                      <label for="email" class="col-sm-2 col-form-label">Email</label>
                      <div class="col-sm-7">
                        <input type="email" class="form-control" id="email" name="email" value="{{request.POST.email}}" required>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="first_name" class="col-sm-2 col-form-label">First Name</label>
                      <div class="col-sm-7">
                        <input type="text" class="form-control" id="first_name" name="first_name" value="{{request.POST.first_name  }}" required>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="middle_name" class="col-sm-2 col-form-label">Middle Name</label>
                      <div class="col-sm-7">
                        <input type="text" class="form-control" id="middle_name" name="middle_name"  value="{{request.POST.middle_name}}" required>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="last_name" class="col-sm-2 col-form-label">Last Name</label>
                      <div class="col-sm-7">
                        <input type="text" class="form-control" id="last_name" name="last_name" value="{{request.POST.last_name}}" required>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="last_name" class="col-sm-2 col-form-label">Phone</label>
                      <div class="col-sm-7">
                        <input type="number" class="form-control" id="phone" name="phone" value="{{request.POST.phone}}" required>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="last_name" class="col-sm-2 col-form-label">Other Phone</label>
                      <div class="col-sm-7">
                        <input type="number" class="form-control" id="phoneb" name="phoneb" value="{{request.POST.phoneb}}" required>
                      </div>
                    </div>
  
                    <div class="row mb-3">
                      <label for="coutry" class="col-sm-2 col-form-label">Sex</label>
                      <div class="col-sm-7">
                          <select class="form-select" aria-label="Default select example" id="gender" name="gender"  required>
                              {%for val in gender%}
                                {%if val.value == request.POST.gender%}
                                  <option value="{{val.value}}" selected>{{val.name}}</option>
                                {%else%}
                                  <option value="{{val.value}}">{{val.name}}</option>
                                {%endif%}
                              {%endfor%}
                            </select>
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="coutry" class="col-sm-2 col-form-label">Country</label>
                      <div class="col-sm-7">
                          <select class="form-select" aria-label="Default select example" id="coutry" name="coutry"  required>
                              {%for val in city%}
                                {%if val.value == request.POST.coutry%}
                                  <option value="{{val.value}}" selected>{{val.name}}</option>
                                {%else%}
                                  <option value="{{val.value}}">{{val.name}}</option>
                                {%endif%}
                              {%endfor%}
                            </select>
                      </div>
                    </div>
                  {%include 'collapse/floor_collapse.html'%}
          </div>
              {%if not success%}
                 <input type="hidden" name="registor" value="detail" >
              {%else%}    
                  <nav class="navbar navbar-expand-lg bg-body-tertiary ">
                  <div class="container-md">
                  <label for="" class="navbar-brand " id="title_detail" > Account password</label>
                  </div>
                  </nav><br>
                  <input type="hidden" name="registor" value="account" >    
                  <div class="row mb-3">
                    <label for="middle_name" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-7">
                      <input type="password" class="form-control" id="middle_name" name="password" required>
                    </div>
                  </div>
                  <div class="row mb-3">
                    <label for="middle_name" class="col-sm-2 col-form-label">Conform Password</label>
                    <div class="col-sm-7">
                      <input type="password" class="form-control" id="middle_name" name="passwordcon" required>
                    </div>
                  </div>
              {%endif%}
              <div class="col-sm-10">
                {% include 'button/main_btn_center.html'%}
              </div>
        </form>
    </div>
    {% include 'container/floor_container.html'%}
</div>
{% include 'container/floor_container.html'%}

{%endblock%}

messager/templates/button/main_btn_center.html
<div class="text-center">
    <input type="submit" value="Submit" class="btn btn-secondary btn-md" id="btn_form">
</div>

messager/templates/button/main_btn_left.html
<div>
    <input type="submit" value="Submit" class="btn btn-secondary" id="btn_form">
</div>

messager/templates/collapse/floor_collapse.html
{%load static%}
</div>
<script src = "{% static 'js/collapse.js' %}"></script>

messager/templates/collapse/top_collapse.html
{%load static%}

    <button class="btn "  type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"><img src="{%static 'img/drop_down.png' %}" height="10px" width="30px" alt="" srcset=""></button>

<div  class="collapse" id="collapseExample">

messager/templates/container/floor_container.html
<div class="col-sm-1">
    <!-- Column -->
  </div>
</div>
</div>

messager/templates/container/top_container.html
<div class="container">
    <div class="row">
      <div class="col-sm-1">
        <!-- Column -->
      </div>

messager/templates/includes/main_axios.html
{%load static%}
<script src = "{% static 'js/axios.min.js' %}"></script>
<script src = "{% static 'js/axios.min.js.map' %}"></script>

messager/templates/includes/main_jquery.html
{%load static%}
<script src = "{% static 'js/jquery-3.6.3.min.js' %}"></script>

messager/templates/includes/main_slick.html
{%load static%}
<link   href= "{% static 'slick-1.8.1/slick/slick.css' %}" rel="stylesheet">
<link   href= "{% static 'slick-1.8.1/slick/slick-theme.css' %}" rel="stylesheet">


<script src = "{% static 'js/jquery-1.11.0.min.js' %}"></script>
<script src = "{% static 'js/jquery-migrate-1.2.1.min.js' %}"></script>
<script src = "{% static 'slick-1.8.1/slick/slick.min.js' %}"></script>

messager/templates/main_footer.html
{% include 'toast/main_toast.html'%}  
</body>
</html>

messager/templates/main_header.html
{%load static%}
<!DOCTYPE html>
<html lang="en">     
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link   href= "{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src = "{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
	
    <link   href= "{% static 'css/title_detail.css' %}" rel="stylesheet">
    <link   href= "{% static 'css/btn_form.css' %}" rel="stylesheet">

messager/templates/main_index.html
{%load static%}
{% include 'main_header.html'%}
{%block index%}

{%endblock%}
{% include 'main_footer.html'%}

messager/templates/navbar/home_navbar.html
{%load static%}
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-light p-4">
    <img src="{% static 'img/messeger.png' %}" width="50" height="50" alt="" srcset="">
    <a class="navbar-brand" href="{%url 'chat:homepage'%}">Messager</a>
    <a class="navbar-brand" href="{%url 'client:logout'%}">Logout</a>
    
    <h5 class="text-dark h4">Messager content</h5>
    <span class="text-body-secondary">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-light ">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span> MENU
    </button>
    <small>{{ request.session.full_name }}<img src="{% static 'img/user.png' %}" width="50" height="50" alt="" srcset=""> </small> 
  </div>
</nav>

messager/templates/navbar/main_navbar.html
{%load static%}
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <img src="{% static 'img/messeger.png' %}" width="50" height="50" alt="" srcset="">
        <a class="navbar-brand" href="{%url 'client:logout'%}">Logout</a>
        <a class="navbar-brand" href="{%url 'client:login'%}">Messager</a>
        <p>
          {{ request.session.account_email }}
        </p>
      </div>
    </nav>
  </div>